# Generated by Django 4.0.3 on 2022-05-05 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.UUID('19bd627e-bd69-48d0-a627-4fd148ec7d44'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_id',
            field=models.UUIDField(default=uuid.UUID('fd1a32bc-838a-4d59-b50f-353bf73a77dd'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_id',
            field=models.UUIDField(default=uuid.UUID('e59b211a-7d84-476b-adac-c6abf1aa90cb'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='financeaccount',
            name='account_id',
            field=models.UUIDField(default=uuid.UUID('2770f0cb-29e4-4a98-a17c-fdc228206d42'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_id',
            field=models.UUIDField(default=uuid.UUID('a44a6464-ef8b-46bf-901b-465a33f43709'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_id',
            field=models.UUIDField(default=uuid.UUID('da85bc94-3e01-4bb2-b77a-753d565bc2a0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='showing_id',
            field=models.UUIDField(default=uuid.UUID('b5dd5d22-5df0-4663-a70a-a3f9c6c118ed'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionID',
            field=models.UUIDField(default=uuid.UUID('21ad4a26-a1da-4d33-8ec2-aa36bc5c8aec'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
