# Generated by Django 4.0.3 on 2022-05-05 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0003_alter_booking_booking_id_alter_club_club_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.UUID('f25e471d-8138-4237-9209-a8ca81f1e5c0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_id',
            field=models.UUIDField(default=uuid.UUID('5063eab3-1c53-438f-8450-f2b5e4c26dfb'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_id',
            field=models.UUIDField(default=uuid.UUID('c90b00da-b598-4dc3-8100-dddf83ebb700'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='financeaccount',
            name='account_id',
            field=models.UUIDField(default=uuid.UUID('b929bbe8-b7ac-4c8d-b5a0-e2e8a619944a'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_id',
            field=models.UUIDField(default=uuid.UUID('0df75637-fb5c-41af-bbd9-3d4ddeb7885b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_id',
            field=models.UUIDField(default=uuid.UUID('ad451dc2-8e8b-4b79-96a6-0a2dd866d170'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='showing_id',
            field=models.UUIDField(default=uuid.UUID('81033071-219b-4862-9608-02210ff30d5f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionID',
            field=models.UUIDField(default=uuid.UUID('4746879b-42ba-471d-8418-8a9b23cb4214'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
