# Generated by Django 4.0.3 on 2022-05-05 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0004_alter_booking_booking_id_alter_club_club_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.UUID('fad16b91-70d5-419f-bb6a-552d5dd38820'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_id',
            field=models.UUIDField(default=uuid.UUID('c6e78653-3b8d-4331-a726-980470ef1b9f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='', max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='', max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_id',
            field=models.UUIDField(default=uuid.UUID('51020e5d-7252-484e-83fa-8788ad369051'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='financeaccount',
            name='account_id',
            field=models.UUIDField(default=uuid.UUID('55ec0302-ae21-45da-a173-476e6105e3e7'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_id',
            field=models.UUIDField(default=uuid.UUID('a3e232db-f156-45fe-ae6a-62308e7329e4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_id',
            field=models.UUIDField(default=uuid.UUID('ac2c0309-7f50-422a-91b9-e0f455f0edfc'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='showing_id',
            field=models.UUIDField(default=uuid.UUID('b161f8e8-5927-48ea-a497-e5cfd9a67b61'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionID',
            field=models.UUIDField(default=uuid.UUID('a63bd909-70f6-4863-881a-dbdbeb2b02bc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
