from django import views
from django.urls import path
from loginSystem import views

urlpatterns = [
    path("", views.home, name="home"),
    path("logout/", views.userLogout, name="logout"),
    path("loginPage/", views.user_login, name="loginPage"),
    path("cinemaManagerPage/", views.cinema_manager_page, name="cinemaManagerPage"),
    path("accountManagerPage/", views.account_manager_page, name="accountManagerPage"),
    path("employeePage/", views.employee_page, name="employeePage"),
    path("clubRepPage/", views.club_rep_page, name="clubRepPage"),
    path("registerPage/", views.register_user, name="registerPage"),
    path("addFilmPage/", views.add_film_page, name="addFilmPage"),
    path("addScreenPage/", views.add_screen_page, name="addScreenPage"),
    path("addShowingPage/", views.add_showing_page, name="addShowingPage"),
    path("films/", views.FilmList.as_view(), name="films"),
    path("screens/", views.ScreenList.as_view(), name="screens"),
    path("showings/", views.ShowingList.as_view(), name="showings"),
    path("filmShowings/", views.view_film_showings, name="filmShowings"),
    path("deleteFilm/", views.delete_film, name='deleteFilm'),
    path("deleteScreen/", views.delete_screen, name='deleteScreen'),
    path("deleteShowing/", views.delete_showing, name='deleteShowing'),
    path("buildSeats/", views.build_seats, name="buildSeats"),
    path("seats/", views.show_seats, name="seats"),
    path("applications/", views.applications, name="applications"),
    path("applications/viewAppData", views.viewAppData, name="viewAppData"),
    path("applications/acceptUserApplication", views.acceptUserApplication, name="acceptUserApplication"),
    path("applications/rejectUserApplication", views.rejectUserApplication, name="rejectUserApplication"),
    path("addCredits/", views.addCredits, name="addCredits"),
    path("payWithCard/", views.payWithCardUnauth, name="payWithCard"),
    path("confirmBooking/", views.confirm_booking, name="confirmBooking"),
    path("bookingConfirmed/", views.booking_confirmed, name="bookingConfirmed"),
    path("topUp/", views.topUp, name="topUp"),
    path("topUpPayment/", views.topUpCard, name="topUpPayment"),
    path("topUpSuccess/", views.topUpSuccess, name="topUpSuccess"),
    path("cancelBooking/", views.cancelBooking, name="cancelBooking"),
    path("cancelBooking/cancelBookingProcess", views.cancelBookingProcess, name="cancelBookingProcess"),
    path("transactions/", views.view_transactions, name="transactions"),
    path("clubPage/", views.menuForClubPage, name="clubPage"),
    path("createClubDetails/", views.createClubDetails, name="createClubDetails"),
    path("showClubDetails/", views.showClubDetails, name="showClubDetails"),
    path("editClubDetails/<uuid:pk>/", views.editClubDetails, name="editClubDetails"),
    path("deleteClubDetails/<uuid:pk>/", views.deleteClubDetails, name="deleteClubDetails"),
    path("editShowings/<uuid:pk>/", views.editShowingsView, name="editShowings"),
    path("download/", views.downloadReport, name="download"),
    path("accounts/", views.accounts, name="accounts"),
    path("editAccount/<uuid:pk>/", views.edit_account, name="editAccount"),
    path("cancelBooking/", views.cancelBooking, name="cancelBooking"),
    path("cancelBooking/cancelBookingProcess", views.cancelBookingProcess, name="cancelBookingProcess"),
    path("cancellations", views.cancellations, name="cancellations"),
    path("viewBookingData", views.viewBookingData, name="viewBookingData"),
    path("viewCancellationRequests", views.cancellations, name="viewCancellationRequests"),
    path("processCancellationRequest", views.processBookingCancellation, name="processBookingCancellation"),
]


# https://www.youtube.com/watch?v=pLN-OnXjOJg&t=0s
